// Writes docs/prompts.md from the live prompt builders so the submitted prompts are exactly what the app runs.
import { writeFileSync } from 'node:fs';
import { scorerSystemPrompt, scorerUserMessage, RULES } from '../app/lib/rules.js';
import { generatorSystemPrompt } from '../app/lib/generator.js';
const ex = scorerUserMessage({ adText: 'HEADLINE: <headline>\nBODY: <body>\nCTA: <cta>', preHits: [{ rule_id: 'P1', span: 'cures acne' }], product: null, mode: 'any' });
const md = `# Prompts the app uses

Generated by \`node scripts/dump-prompts.js\` from the live prompt builders in \`app/lib/rules.js\` and \`app/lib/generator.js\`. Do not edit by hand. Rules version ${RULES.version}.

The scorer prompt is rendered from \`rules/brand-rules.json\`; the rulebook section below is that file, flattened. The model returns JSON matching the schema in \`app/lib/scorer.js\` (findings with rule_id / span / explanation / fix / on_source_page, three dimension summaries, an optional rewrite, and a not_checked list). Severity and verdict are computed server-side from the rules file, not taken from the model.

---

## 1. Scorer — system prompt (mode: any)

\`\`\`
${scorerSystemPrompt('any')}
\`\`\`

## 2. Scorer — user message shape

\`\`\`
${ex}
\`\`\`

In generator mode the same message adds a "SOURCE PRODUCT PAGE FACTS" block and the MODE line says G1 applies.

## 3. Generator — system prompt

\`\`\`
${generatorSystemPrompt()}
\`\`\`

## 4. Generator — user message shape

\`\`\`
## SOURCE FACTS
Title: …
Active: … · Concentration: …
Price: … · Size: …
Tags: …
Claims:
- …
Study stats:
- …
Safety / suitability:
- …
Provenance:
- …
Labelled fields: {…}

Write the ad.
\`\`\`
`;
writeFileSync('docs/prompts.md', md); console.log('wrote docs/prompts.md', md.length, 'chars');
