"""Writes docs/prompts.md from the live prompt builders so the submitted prompts are exactly what the app runs."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.rules import scorer_system_prompt, scorer_user_message, RULES  # noqa: E402
from app.generator import generator_system_prompt  # noqa: E402

ex = scorer_user_message("HEADLINE: <headline>\nBODY: <body>\nCTA: <cta>", [{"rule_id": "P1", "span": "cures acne"}], None, "any")
md = f"""# Prompts the app uses

Generated by `python scripts/dump_prompts.py` from the live prompt builders in `app/rules.py` and `app/generator.py`. Do not edit by hand. Rules version {RULES['version']}.

The scorer prompt is rendered from `rules/brand-rules.json`; the rulebook section below is that file, flattened. The model returns JSON matching the Pydantic schema in `app/scorer.py` (findings with rule_id / span / explanation / fix / on_source_page, three dimension summaries, an optional rewrite, and a not_checked list). Severity and verdict are computed server-side from the rules file, not taken from the model.

---

## 1. Scorer — system prompt (mode: any)

```
{scorer_system_prompt('any')}
```

## 2. Scorer — user message shape

```
{ex}
```

In generator mode the same message adds a "SOURCE PRODUCT PAGE FACTS" block and the MODE line says G1 applies.

## 3. Generator — system prompt

```
{generator_system_prompt()}
```

## 4. Generator — user message shape

```
## SOURCE FACTS
Title: …
Active: … · Concentration: …
Price: … · Size: …
Tags: …
Claims:
- …
Study stats:
- …
Safety / suitability:
- …
Provenance:
- …
Labelled fields: {{…}}

Write the ad.
```
"""
Path("docs/prompts.md").write_text(md, encoding="utf-8"); print("wrote docs/prompts.md", len(md), "chars")
